name: fredit
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  google_sign_in: ^6.1.4
  firebase_storage: ^11.2.5
  flutter_riverpod: ^2.3.6
  cloud_firestore: ^4.8.4
  fpdart: ^1.0.0
  routemaster: ^1.0.1
  flutter_vector_icons: ^2.0.0
  dotted_border: ^2.0.0+3
  file_picker: ^5.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
