// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhLrWYkYj3F0RDrL7d4pK6rbdIx1jOCJI',
    appId: '1:681329727544:web:016218c8968570734deecd',
    messagingSenderId: '681329727544',
    projectId: 'fredit',
    authDomain: 'fredit-df21b.firebaseapp.com',
    storageBucket: 'fredit.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKekxEsvec-v8F0x-Q7qU3beideKKKapw',
    appId: '1:681329727544:android:265580cc14b417654deecd',
    messagingSenderId: '681329727544',
    projectId: 'fredit',
    storageBucket: 'fredit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB20iIXkqw57VumwLSEAvwmL1p8MrR7nR0',
    appId: '1:681329727544:ios:8b55fa30eed05c684deecd',
    messagingSenderId: '681329727544',
    projectId: 'fredit',
    storageBucket: 'fredit.appspot.com',
    iosClientId: '681329727544-27k7mbo6tua5ha7rrhebfffv3lviq4ke.apps.googleusercontent.com',
    iosBundleId: 'com.example.fredit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB20iIXkqw57VumwLSEAvwmL1p8MrR7nR0',
    appId: '1:681329727544:ios:8cfccb760a775f344deecd',
    messagingSenderId: '681329727544',
    projectId: 'fredit',
    storageBucket: 'fredit.appspot.com',
    iosClientId: '681329727544-cbrrv1rigckvn8dfheh6j6vsnrsaa9gf.apps.googleusercontent.com',
    iosBundleId: 'com.example.fredit.RunnerTests',
  );
}
